embed_dim: 100
dropout_rate: 0.1
encoder_dims: [400, 400, 100]
activation: tanh
anneal_max: 0.2
anneal_total_step: 200000
share_item_encoder: 1

stage: 0
learn_sigma: False
sigma_small: False
diffusion_steps: 500
noise_schedule: cosine
timestep_respacing: 'ddim250'
use_kl: False
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False
schedule_sampler: uniform
kl_lambda: 1e-4
clip_denoised: False
use_ddim: True

learning_rate: 2e-3
weight_decay: 1e-6
learner: adam
epochs: 1000
batch_size: 512
eval_batch_size: 512
early_stop_patience: 50
