embed_dim: 100
dropout_rate: 0.1
encoder_dims: [400, 400, 100]
activation: tanh
beta_max: 0.02
beta_min: 0.0001
num_steps: 200
mask_rate: 0.1

learning_rate: 0.001
weight_decay: 1e-6
learner: adam
epochs: 1000
batch_size: 128
eval_batch_size: 128
early_stop_patience: 50
