embed_dim: 100
dropout_rate: 0.1
encoder_dims: [400, 400, 100]
activation: tanh
share_item_encoder: 1
stage: 0
beta_max: 20.0
beta_min: 0.1
scale: 5.0
num_steps: 500
snr: 0.16

anneal_max: 0.2
anneal_total_step: 200000

learning_rate: 0.001
weight_decay: 0
learner: adam
epochs: 1000
batch_size: 512
eval_batch_size: 512
early_stop_patience: 50
