embed_dim: 100
dropout_rate: 0.5
encoder_dims: [200,100]
activation: tanh

anneal_max: 2
anneal_total_step: 2000
kfac: 7
tau: 0.1
std: 0.1
nogb: False
reg_weights: 1e-4


learning_rate: 0.001
weight_decay: 0
learner: adam
epochs: 1000
batch_size: 256
eval_batch_size: 256
early_stop_patience: 100