embed_dim: 100
dropout_rate: 0.5
encoder_dims: [200,100]
activation: tanh

anneal_max: 0.2
anneal_total_step: 2000000
kfac: 7
tau: 0.1
std: 0.075
nogb: False
reg_weights: 1e-4


learning_rate: 0.001
weight_decay: 0
learner: adam
epochs: 200
batch_size: 256
eval_batch_size: 200
negative_count: 1000
# negative_count: [2000, 1000]  # DNS, SIR
# negative_count: [1000, 500]  # DNS


test_metrics: [ndcg, recall, precision, map, mrr, hit]
val_metrics: [ndcg, recall]
topk: 100
cutoff: [20, 50, 100]