dropout: 0.5
hidden_dim: 200
latent_dim: 200
activation: relu

gamma: 0.005
beta: 0.005

alternating: True
enc_epoch: 3
dec_epoch: 1

learning_rate: 0.001
weight_decay: 1e-5
learner: adam
epochs: 200
batch_size: 256
eval_batch_size: 200
negative_count: 1000
# negative_count: [2000, 1000]  # DNS, SIR
# negative_count: [1000, 500]  # DNS


test_metrics: [ndcg, recall, precision, map, mrr, hit]
val_metrics: [ndcg, recall]
topk: 100
cutoff: [20, 50, 100]